### ISSUE TITLE
Inconsistent workspace code for lab 10 (Snake)

### ISSUE THREAD

**Issue by johanneshardt** [lunduniversity/introprog#710]
There are two small issues i've noticed with the current workspace code for lab 10:
- The signature of the play() method in `SnakeGame` doesn't match the ones in the subclasses `OnePlayerGame`/`TwoPlayerGame`, which results in compilation errors when using `override`. 
- In `Player.scala`, the instances of the enum `KeyMap`, `Letters` and `Arrows`, don't match the inputs provided by `onKeyDown()`, i.e. pressing w/a/s/d or Left/Right/Down/Up doesn't work without correcting the spelling in `KeyMap`.

I could make a small PR with the changes if it seems reasonable.

**Comment by johanneshardt** [comment]
Regarding the first point, it seems it was caused by dbb6b0dc41e37f1180a9560ccd99cfc0b0ee3b18
